# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 647401bb833b372c1ea7d6eb320971c9080c1a993ffdbd06c7e2405ddda2eb7a5501cab70eb2625832064bf9363d2dfaba259caa94bfb181798be68c6232139e

test:
  secret_key_base: a4b65b3044947acd9ba5709cb7e0c7dc39a6fb04791ac0a33a2afc4a388e672d9fb4f2bd70b4ff7eb55893812e91f9674f0cfe9f025fb4895e47749547ecb6d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
